###
POST http://localhost:3000/payment 
content-type: application/json

{
  "items": [
    {
      "title": "chinchenhanchin",
      "quantity": 3,
      "unit_price": 0.01,
      "id": "awdawdawsdawsd"
    },
    {
      "title": "wasa",
      "quantity": 10,
      "unit_price": 0.01,
      "id": "awsdawdawsd"
    },
    {
      "title": "wwwwwwwwwwwwwwwwwww",
      "quantity": 10,
      "unit_price": 0.01,
      "id": "awdawdawsd"
  
    }
  ],
  "payer": {
    "name": "Balatro",
    "surname": "Balatrez",
    "email": "balatrodelosbalatrez@gmail.com",
    "id": "asedfopakfpas"
  }
}